# Default values for sbo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
namespace: default

image:
  repository: quay.io/akashshinde/nodejs-todo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

application:
  name: todo-app

backend:
  name: etcd-cluster

etcd:
  size: 2

sbo:
  detectBindingResources: true

